version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: berberco_postgres
    environment:
      POSTGRES_DB: barber_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: berberco_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
  kafka_data:
  kafka_meta:
