server:
  port: 8080

spring:
  application:
    name: barber-co
  datasource:
    url: jdbc:postgresql://localhost:5434/barber_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/barber_co
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "com.berber_co.barber.service.notification.NotificationMessage"
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "com.berber_co.barber.service.notification.NotificationMessage"
      group-id: notification-group
    template:
      default-topic: appointment-notification

security:
  jwt:
    secret: 0
    expiration: 3600000
    access-expiration: 604800000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: ERROR
